iterative/terraform-provider-iterative

- README.md
Improves Docs.
Adds Usage with:
- step by step terraform introduction
- examples
> Docs usage with examples

- examples/main.tf
- iterative/resource_machine.go
> Machine missing input param

- iterative/aws/provider.go
> AWS delete error when no instances

- iterative/resource_runner.go
> Docker home

- iterative/resource_runner.go
Runs CML as a service to be able to respond to any shutdown event like 
- stop / start
- terminate
- terraform destroy
- spot instances
closes #34 
closes https://github.com/iterative/cml/issues/368
> graceful shutdown

- iterative/resource_runner.go
Adds the AWS to the runner to be able to destroy the instance.
closes https://github.com/iterative/cml/issues/416
> Adds AWS session tokens

- .github/workflows/test.yml
This pull request adds a new GitHub Actions workflow to run tests on every pull request or push event.
> Add automated testing workflow

- cml/clone-amis.go
Requested by @btjones-me [on Discord](https://discord.com/channels/485586884165107732/728693131557732403/817195215668248616).
> Clone AWS CML machine image to eu-west-2

- iterative/resource_runner.go
- iterative/resource_runner_test.go
Adds custom startup script into our script before creating and launching CML service 
closes #74
> Runner startup script

- iterative/aws/provider.go
- iterative/resource_runner.go
This PR is the missing part to solve #72 !
I missed to upload the provider code somehow
> AWS fallback ubuntu

- iterative/resource_machine.go
- iterative/resource_runner.go
> Mark keys as sensitive

- cml/clone-amis.go
Each `clone-amis.go` run took eons to process, but now it takes a single eon no matter how many regions we want to support.
> Parallelize clone-amis.go

- iterative/aws/provider.go
> Add more AWS regions

- iterative/utils/ssh.go
* Use CombinedOutput for capturing SSH output (#108)
> Release v0.6.2 (#108)

- README.md
- iterative/aws/provider.go
- iterative/azure/provider.go
- iterative/kubernetes/provider.go
- iterative/resource_runner.go
Fixes iterative/cml#509 in combination with iterative/cml#540
> Rename instance_gpu tesla to v100

- iterative/resource_runner.go
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_invalid.golden
> Install build-essential on ground-up provisioning

- iterative/resource_runner.go
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_invalid.golden
> Install ubuntu-drivers-common before running ubuntu-drivers

- README.md
- update iterative logo (fixes #117)
- add transparency for dark theme (related https://github.com/iterative/cml/issues/533)
> update banner logo & theme

- README.md
Minor updates based on trying out machine example
> Tweak readme machine example

- iterative/resource_runner.go
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_invalid.golden
Fixes https://github.com/iterative/cml/issues/590
> Remove ppa:graphics-drivers/ppa

- .github/workflows/test.yml
I added triggers for both `push` and `pull_request` but the former was redundant.
> Simplify test.yml

- iterative/resource_runner.go
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_invalid.golden
Fixes #90; tested, but still requires another pair of eyes.
> Fix cml.service not waiting for process shutdown

- iterative/gcp/provider.go
> Add support for GOOGLE_APPLICATION_CREDENTIALS on runners

- .goreleaser.yml
Should fix #177, but I haven't tested it yet.
> Add Windows to the list of release targets

- README.md
> Mention the Terraform JSON Configuration Syntax

- iterative/resource_machine.go
- iterative/resource_runner.go
Part of https://github.com/iterative/terraform-provider-iterative/issues/185
> Add support for generic metadata

- iterative/gcp/provider.go
Part of https://github.com/iterative/terraform-provider-iterative/issues/185
> Add support for Google Cloud metadata (labels)

- README.md
To be merged against #248, follow–up of https://github.com/iterative/terraform-provider-iterative/pull/248#issuecomment-971907543.
**Depends on**
* https://github.com/iterative/terraform-provider-iterative/pull/251
* https://github.com/iterative/terraform-provider-iterative/pull/250 (optional)
> Development guide

- docs/guides/getting-started.md
- docs/index.md
- docs/resources/task.md
> Fix colons on documentation callouts

- task/common/machine/script.go
> Fix typo on `iterative_task` agent install process

- .github/workflows/smoke.yml
> Mask temporary kubeconfig from logs

- .github/workflows/smoke.yml
#271 broke the tests because GitHub won't allow users to pass a secret between jobs. 🤦🏼‍♂️
> Fix k8s test fixture

- .github/workflows/smoke.yml
> Add name to k8s test

- .github/workflows/smoke.yml
- task/task_test.go
...lest upsetting cloud providers
> Add sleep on test polling loops

- task/task_test.go
Otherwise, tests can be flaky... sometimes. ❄️
> Wait for data to be synchronized before exiting

- .github/workflows/smoke.yml
> Checkout target branch on smoke tests

- iterative/aws/provider.go
- iterative/azure/provider.go
- iterative/gcp/provider.go
- iterative/kubernetes/provider.go
🤦🏼 Regression introduced with #237
> Fix machine instance types

- .github/workflows/smoke.yml
> test(k8s): move test cluster to westus

- docs/guides/getting-started.md
- docs/index.md
- docs/resources/task.md
- tabulate generic images (part of #267 but doesn't yet fully resolve)
- misc copyediting
- typos
- formatting consistency
- line wrapping consistency
- minor rewording
- `terraform fmt`
> copyediting

- task/common/machine/script.go
- related #280 <- #266 <- #231
> make Python optional

- docs/resources/task.md
> Document image requirements

- iterative/aws/provider.go
> Fix Iterative regions in AWS

- docs/resources/task.md
Thanks for noticing it, @MKhalusova! 🙏🏼
> Fix order of parameter for custom machine images

- iterative/resource_task.go
- task/common/machine/script.go
- Adds CI env variables
- Adds TPI_TASK env var
- Installs cml
- Restart CI pipeline on completion if is in CI 
- closes #324
> CML sugar 🍬 

- iterative/resource_task.go
> Dir out must be empty if no equals in

- iterative/aws/provider.go
~Leaving as draft until I test the changes.~ @dabcd already did! 🎉
> Search for security group identifiers instead of names if they start with sg-

- README.md
> update discord link again

- iterative/resource_runner.go
Part of https://github.com/iterative/cml/issues/772
> Move runner startup script under the right heredoc

- docs/guides/testing-kubernetes.md
Not sure if [`subcategory`](https://www.terraform.io/docs/registry/providers/docs.html#example) works for guides. 🙈
> Add AKS guide for testing Kubernetes support

- task/common/machine/script.go
> Fix data directory synchronization

- README.md
- docs/guides/getting-started.md
- docs/index.md
- docs/resources/task.md
- iterative/resource_task.go
> Use randomly generated identifiers by default

- .github/workflows/smoke.yml
> Add environment to all the smoke test steps

- README.md
Per last week's release meeting and decision to combine CML and TPI into one channel.  Using Elle's old link even though it's longer, because it has analytic history already.
> Discord link update - third times a charm - Update README.md

- go.mod
- iterative/utils/logger.go
> Fix multiple resources logs

- task/aws/resources/resource_bucket.go
Closes #454; see the issue for context.
> Fix `aws` bucket creation failure on `us-east-1`

- task/common/machine/storage.go
See https://github.com/iterative/terraform-provider-iterative/pull/467#discussion_r839871754
> Increase data transfer progress interval to 10 s

- docs/guides/getting-started.md
- docs/resources/task.md
> Document `name` and `id`

- iterative/utils/logger.go
- task/aws/task.go
- task/az/task.go
- task/gcp/task.go
- task/k8s/task.go
Part of https://github.com/iterative/terraform-provider-iterative/issues/481
> Log “experience” changes

- task/aws/resources/resource_auto_scaling_group.go
- task/az/resources/resource_virtual_machine_scale_set.go
- task/gcp/resources/resource_instance_group_manager.go
I was lucky enough to reproduce some waiter bugs consistently during the debugging of #482. Closes #462 for AWS.
> Improve AWS AutoScaling group waiter conditions

- .github/workflows/build-ami.yml
This pull request adds triggers to rebuild the AMI when commits contain changes to the `environment` directory and fixes the workflow, which was missing the `packer init` command. 🙈
> Fix build-ami workflow

- .devcontainer.json
I'll thank it the next time we have to solve some fire quickly 🔥
> Add packer to devcontainer.json

- iterative/utils/logger.go
Let me slide this typo I found in with the docs pr
> logging typo

- task/task_test.go
More idiomatic and helpful to debug flaky tests
> Replace `.Nil` by `.NoError` in tests

- task/aws/task.go
- task/az/task.go
- task/gcp/task.go
- task/k8s/task.go
> Add “this may happen several times” notice on Read

- task/aws/resources/data_source_image.go
The best we can do to fix #524
> Use AWS DLAMI instead on NVIDIA NGC

- docs/guides/generic-machine-types.md
- task/gcp/resources/resource_instance_template.go
- task/k8s/resources/resource_job.go
> remove s+k80

- task/common/machine/script.go
Introduces https://github.com/iterative/terraform-provider-iterative/pull/318#issuecomment-982728169 to avoid appearing as `queued` when the script fails. 🙈
> Fix `ExecStop` condition

- task/common/machine/script.go
This should disable automatic updates on Ubuntu machines, as in @casperdcl's use case repository.
> Disable `apt-daily.timer`

- README.md
- docs/guides/generic-machine-types.md
- docs/guides/getting-started.md
- docs/index.md
- docs/resources/task.md
- NVIDIA images (fixes #410)
- typos, copyediting
- missing clouds
- task defaults (fixes #347)
- mention auto-termination on completion/error
- misc follow-ups (fixes #513)
+ low-level mermaid stages
+ Stop -> End
+ mention reproducible, codified environments
+ better CML links
+ explicit auto-backup
> docs: iter 4

- README.md
- docs/guides/getting-started.md
A bit rough, would ideally like to record properly but AWS is being slow today.
Can always update later.
> docs: add GIF & video

- README.md
- docs/index.md
> docs: minor section rename

- .github/workflows/smoke.yml
* https://github.com/iterative/terraform-provider-iterative/pull/552#discussion_r864868215
> Port `github.ref_name` to smoke.yml

- iterative/gcp/provider.go
> Escape dots in GCP OIDC regular expression

- README.md
- docs/guides/authentication.md
- docs/guides/getting-started.md
> Simplify Readme

- task/common/machine/script.go
Closes https://github.com/iterative/terraform-provider-iterative/issues/565; opens #570
> Fix NVIDIA APT GPG keys

- README.md
- docs/guides/authentication.md
- docs/index.md
- add example projects/blogs
- make permission reference links more visible
- note more future plans
> add example projects/blogs

- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
Feels like some easy low hanging fruit, to make docs iterations _slightly_ faster
> Adjust some actions triggers

- iterative/resource_task.go
- iterative/utils/logger.go
- iterative/utils/logger_test.go
This pull request fixes a regression introduced with #567 and (slightly) tries to improve the overall approach to logging. There is still material for three more pull requests.
> Reconcile loggers

- task/common/machine/script.go
- task/common/machine/storage.go
> Use global timeout on `aws`, `az` & `gcp`

- .github/workflows/smoke.yml
This will allow us to catch & reproduce flaky issues earlier
> Increase smoke test frequency to daily

- environment/setup.sh
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_gcp.golden
- iterative/testdata/script_template_cloud_invalid.golden
Adds `acpid` to the runner's host
> Runner acpid

- environment/setup.sh
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_gcp.golden
- iterative/testdata/script_template_cloud_invalid.golden
> Remove incompatible options from `systemd-run`

- iterative/utils/analytics.go
- iterative/utils/analytics_test.go
Also added a few minor testify usage cleanups.
Isolated UserId test to not polute XDG_CONFIG_HOME
> Fix failing UserId test

- task/aws/resources/data_source_credentials.go
- task/aws/resources/resource_launch_template.go
- task/aws/task.go
- task/az/resources/data_source_credentials.go
- task/az/resources/resource_virtual_machine_scale_set.go
- task/az/task.go
- task/common/machine/machine-script.sh.tpl
- task/common/machine/script.go
- task/common/machine/script_test.go
- task/common/machine/testdata/machine_script_full.golden
- task/common/machine/testdata/machine_script_minimal.golden
- task/gcp/resources/data_source_credentials.go
- task/gcp/resources/resource_instance_template.go
- task/gcp/task.go
Use embedded template instead of format string.
Add test.
Remove use of map pointer - golang maps are already pointers to a maps structure and can be nil.
> Slight refactoring of machine script generation

- docs/resources/task.md
- task/k8s/resources/data_source_permission_set.go
- task/k8s/resources/resource_job.go
Permission set references a service account in the client's namespace.
This resolves #560.
> Support for permission set in `k8s`

- task/task_smoke_test.go
> Fix smoke test script preamble

- .github/workflows/release.yml
- .goreleaser.yml
Continuation of #672 post-mergem review comments:
* https://github.com/iterative/terraform-provider-iterative/pull/672#discussion_r973107404
* https://github.com/iterative/terraform-provider-iterative/pull/672#discussion_r973106448
> Consolidate release workflow

- .github/workflows/smoke.yml
Should close https://github.com/iterative/terraform-provider-iterative/issues/279 as per https://github.com/iterative/terraform-provider-iterative/issues/279#issuecomment-1253523776
> Move AKS tests to `Standard_NC4as_T4_v3`

- .github/workflows/smoke.yml
Continuation of #680, perisists change from #673 🙈
> Migrate `k8s` smoke test after quota increase approval

- iterative/kubernetes/provider.go
- task/k8s/resources/data_source_permission_set.go
> Handle instance permission set in k8s runner resource

- iterative/utils/analytics.go
Same as https://github.com/iterative/cml/pull/1199
> Exclude internal projects & tests from analytics

- docs/guides/permissions/aws/main.tf
* https://github.com/iterative/terraform-provider-iterative/pull/670#pullrequestreview-1134317993
> Document DescribeInstanceTypeOfferings permission

- environment/setup.sh
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_gcp.golden
- iterative/testdata/script_template_cloud_invalid.golden
Reverts iterative/terraform-provider-iterative#688
requires more testing specifically for GitLab
> Revert "Update nvidia container support package"

- cmd/leo/read/read.go
- task/aws/task.go
- task/az/task.go
- task/gcp/task.go
> Implement `read --follow`

- task/common/machine/machine-script.sh.tpl
- task/common/machine/testdata/machine_script_full.golden
- task/common/machine/testdata/machine_script_minimal.golden
> Remove `cml rerun-workflow`

- task/aws/client/client.go
- task/az/client/client.go
- task/az/resources/data_source_credentials.go
- task/common/cloud.go
- task/gcp/client/client.go
- task/k8s/client/client.go
> Add structure for hardcoded credentials

- task/aws/client/client.go
- task/az/client/client.go
- task/az/resources/data_source_credentials.go
- task/common/cloud.go
- task/gcp/client/client.go
- task/k8s/client/client.go
> Add structure for passing hardcoded credentials to task

- iterative/aws/provider.go
- iterative/azure/provider.go
- iterative/resource_runner.go
- iterative/testdata/script_template_cloud_aws.golden
- iterative/testdata/script_template_cloud_azure.golden
- iterative/testdata/script_template_cloud_gcp.golden
- iterative/testdata/script_template_cloud_invalid.golden
- iterative/testdata/script_template_cloud_kubernetes.golden
- iterative/utils/helpers.go
- iterative/utils/helpers_test.go
> Improve `machine` identifier format

- README.md
- docs/index.md
- as per https://github.com/badges/shields/issues/8671
> update badge URLs

- cmd/leo/destroyrunner/destroyrunner.go
Closes https://github.com/iterative/cml/issues/1330
> Add `leo destroy-runner` cloud aliases for compatibility

- .github/workflows/build-ami.yml
> Fix packer OIDC permissions

- task/common/machine/machine-script.sh.tpl
- task/common/machine/testdata/machine_script_full.golden
- task/common/machine/testdata/machine_script_minimal.golden
Usage: `environment = {TPI_DISABLE_DATA_DIRECTORY_SYNCHRONIZATION = "true"}`
_Requested by @dacbd on [Slack](https://iterativeai.slack.com/archives/C01900GSB4J/p1678389108443619)._
> Add option to disable directory synchronization

- task/common/machine/machine-script.sh.tpl
- task/common/machine/testdata/machine_script_full.golden
- task/common/machine/testdata/machine_script_minimal.golden
`STUDIO_URL` -> `STUDIO_ENDPOINT`
> patch: use same env as dvclive

- task/common/machine/machine-script.sh.tpl
- task/common/machine/testdata/machine_script_full.golden
- task/common/machine/testdata/machine_script_minimal.golden
> Studio - drop name prefix

- task/common/machine/machine-script.sh.tpl
- task/common/machine/testdata/machine_script_full.golden
- task/common/machine/testdata/machine_script_minimal.golden
from the latest release of `dvc-studio-client`
- uses `machine` key
- uses updated env vars
> studio helper update
