README.md, iterative/resource_machine.go
Add ami input. It might be needed by the end user. We will need to add a provisioner function also in order to install custom packages.
=> release/0.5.1 Add ami input to provider

cml/setup.sh, iterative/resource_runner.go
Ubuntu loves to upgrade itself. Those unattended upgrades have to be disabled to not conflict with current installs in workflows. 
closes #20
=> Fix dpkg frontend lock

iterative/aws/provider.go, iterative/azure/provider.go
This PRs fixes the several crashes that can occur due to AWS non present resources.
- Only try to delete if the resource exists. closes #19 
- Warns that VPC and/or subnet is not present
- MInor code cleanup
=> Delete error and other non existing resources check

cml/ami.json, cml/setup.sh, iterative/resource_runner.go
docker-nvidia needs to install nvidia-docker2 opposed to toolkit. Additionally the machine preparation has been set to not need restart
=> GPU support without restart

iterative/resource_runner.go
Changes the cml repo from cml-runner branch to master.
Probably makes sense to do npm package instead.
closes #46
=> CML points to master

iterative/resource_runner.go
Temporary fix for https://github.com/iterative/terraform-provider-iterative/issues/40; should be reverted as soon as https://github.com/docker/cli/pull/2934 gets fixed downstream.
=> Use a temporary home directory for runners

iterative/aws/provider.go
Fixes #77, should not require any other change.
=> Rename AWS security group from cml to iterative

iterative/resource_runner_test.go
I missed this optimization when reviewing #79, sorry. 🤦   It would be nice to take advantage of `testify/assert` expressiveness for string tests by using the inbuilt `Contains` and `NotContains` functions.
=> Migrate string assertion tests to Contains/NotContains

.gitignore, iterative/aws/provider.go
Fixes the issue that AWS seems to be creating with uppercase and lowecase when creating and searching security groups.
Additionally warns in case the user has no permissions to create new SG.
Removes ./terraform-provider-iterative
closes https://github.com/iterative/cml/issues/447
=> No SG found due to casing

iterative/resource_runner.go
This would be extremely useful for debugging some connection issues.
=> Debug the instance IP prior to awaiting the runner

iterative/resource_runner.go, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_invalid.golden
Not required, as per the `systemd` log messages:
> _Configuration file `/etc/systemd/system/cml.service` is marked executable. Please remove executable permission bits._
Closes #98
=> Remove executable bit from the systemd service file

iterative/utils/ssh.go
Fixes a buffer writing bug where the function would return an empty string after a succesful read
=> Use CombinedOutput for capturing SSH output

iterative/resource_runner.go
Related to https://github.com/iterative/cml/pull/564
=> Mark resource_runner token as sensitive

iterative/utils/ssh.go
Triggered when feeding with an invalid key
> ```go
> func Decode(data []byte) (p *Block, rest []byte)
> ```
> [_If no PEM data is found, `p` is `nil` and the whole of the input is returned in rest._](https://golang.org/pkg/encoding/pem/#Decode )
=> Fix nil pointer dereference on SSH key parser

iterative/resource_runner.go, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_invalid.golden
Seems that nvidia needs to be rebooted now. So we are rebooting and enabling cml after reboot, additionally we are adding the latest nvidia ppa.
=> Reboot to enable nvidia

iterative/resource_machine.go, iterative/resource_runner.go
Far from being an ideal solution, it will mitigate some plaintext secret leak issues on errored runs.
=> Mark startup script as sensitive

iterative/resource_runner_test.go
```
--- FAIL: TestScript/AWS_known_region_should_not_add_the_NVIDA_drivers (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1c2e460]
```
=> Fix nil dereferencing on template errors

iterative/aws/provider.go, iterative/azure/provider.go, iterative/resource_runner.go, iterative/resource_runner_test.go
- Ensures that the Ubuntu image is developed by Canonical
- Chooses the default VPC and not the very first one
- Ensures that the subnet can create public IPs and it has available IPs still
- Checks the iterative mapped regions to determine if ami is available. closes #99 
- Sets the used ami name in the tfstate
=> AWS better check and election

iterative/aws/provider.go, iterative/azure/provider.go, iterative/resource_machine.go, iterative/resource_runner.go
- fixes #154 Only displays the service logs 
- fixes #153 Reduces the timeout from 10 to 2
=> Wait improvements

iterative/azure/provider.go
Part of https://github.com/iterative/terraform-provider-iterative/issues/185
=> Add support for Azure metadata (tags)

iterative/aws/provider.go
~Probably discovered by @DavidGOrtega on https://github.com/iterative/terraform-provider-iterative/pull/187#issuecomment-916046982.~ Unrelated: serendipity discovery by @0x2b3bfa0
=> Fix nil pointer derreference on AWS resource destroy

cml/setup.sh
Overlooked when reviewing #170, `sudo` is being applied to `echo` but the redirection operator still has the permissions of the main process.
=> Fix ineffective sudo usage in setup.sh

iterative/gcp/provider.go
I can close the draft if preferred, but I figured I'd put it up for the sake of visibility.
- I can rebase out my go.mod/sum changes caused by `go mod tidy`
Consolidate into one PR?
=> gcp instance service-account

iterative/aws/provider.go
I can close the draft if preferred, but I figured I'd put it up for the sake of visibility.
- I can rebase out my go.mod/sum changes caused by `go mod tidy`
- undo `go fmt` spacing changes?
=> Accept an AWS instance-profile

.goreleaser.yml
We don't need them, and builds are broken
=> Skip windows arm* builds

task/az/resources/resource_virtual_machine_scale_set.go
The [`Time`](https://pkg.go.dev/github.com/Azure/go-autorest/autorest/date#Time) field of [`InstanceViewStatus`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-30/compute#InstanceViewStatus) is a pointer and may be `<nil>` in some edge cases.
Found when manually scaling out the Azure Scale Set while the provider was trying to scale it down. See https://github.com/iterative/terraform-provider-iterative/runs/4306049406?check_suite_focus=true#step:6:50 for the full logs.
```
--- FAIL: TestTask (0.98s)
--- FAIL: TestTask/az (0.98s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ceaea5] …
```
=> Fix unsafe access to event time on Azure

docs/guides/getting-started.md
**Definitely, the project layout should not look similar to _this_**
> ![Captura de pantalla 2021-11-24 a las 0 23 41](https://user-images.githubusercontent.com/11387611/143144542-fe70ec8f-6249-4e8b-b852-cf90b46f1704.png)
=> Turn directory tree into preformatted block

docs/resources/task.md
> 447a138 usage is as follows:
> 
> ```hcl
> resource "iterative_task" "example" {
>   ···
>   environment = {
>     VARIABLE = "value"
>     "GITHUB_*" = ""
>   }
>   ···
> }
> ```
> 
> If the variable value is an empty string (""), the variable name is going to be interpreted as a glob, including all the variables from the host environment.
=> Document environment variable globbing

.github/workflows/smoke.yml
Reverts iterative/terraform-provider-iterative#288
> _ERROR: (VMSizeNotSupported) Virtual Machine size: 'Standard_NC6' is not supported for subscription *** in location 'westus'. The available VM sizes are:_
> </blockquote><details><summary>...</summary>
> * standard_a2
> * standard_a2_v2
> * standard_a2m_v2
> * standard_a3
> * standard_a4
> * standard_a4_v2
> * standard_a4m_v2
> * standard_a5
> * standard_a6
> * standard_a7
> * standard_a8_v2
> * standard_a8m_v2
> * standard_b12ms
> * standard_b16ms
> * standard_b20ms
> * standard_b2ms
> * standard_b2s
> * standard_b4ms
> * standard_b8ms
> * standard_d11
> * standard_d11_v2
> * standard_d12
> * standard_d12_v2
> * standard_d13
> * standard_d13_v2
> * standard_d14
> * standard_d14_v2
> * standard_d15_v2
> * standard_d16_v3
> * …
=> Revert "test(k8s): move test cluster to westus"

task/common/identifier.go, task/common/identifier_test.go
Unless proven otherwise, the creation of different identifiers for the same input string is not possible.
Closes #298
=> Improve identifier generation

.github/workflows/release.yml, .goreleaser.yml
Coming from https://github.com/iterative/terraform-provider-iterative/pull/285#pullrequestreview-817110372, should work as-is, although it hasn't been tested yet.
=> Handle GPG keys without intermediate GitHub Actions

task/common/machine/script.go
Machines weren't being stopped unless the task script finished with a zero exit code.
> [...] _Note that the commands specified in `ExecStop=` are only executed when the service started successfully first. They are not invoked if the service was never started at all, or in case its start-up failed, for example because any of the commands specified in `ExecStart=`_ [...] _failed_ [...] _or timed out. Use `ExecStopPost=` to invoke commands when a service failed to start up correctly and is shut down again. Also note that the stop operation is always performed if the service started successfully, even if the processes in the service terminated on their own or were killed. The stop commands must be prepared to deal with that case._ [...] _For post-mortem clean-up steps use `ExecStopPost=` …
=> Stop machines if task script fails

iterative/gcp/provider.go, iterative/resource_runner.go, iterative/utils/helpers.go
An interesting find from: https://github.com/iterative/cml/issues/834 
@eemelipa thank you for the help, I was worried I introduced a new bug! 😮‍💨 
TPI grabs the GCP credentials from here: https://github.com/iterative/terraform-provider-iterative/blob/66bc9cd08a4ef1b17f068ce7fd296c3065a6c810/iterative/gcp/provider.go#L292-L296
In this case, the user set their [GCP SA creds](https://cml.dev/doc/self-hosted-runners?tab=GCP#cloud-compute-resource-credentials) with the `GOOGLE_APPLICATION_CREDENTIALS`  which is a path to the JSON file which the above code finds via the else clause: https://pkg.go.dev/golang.org/x/oauth2/google#FindDefaultCredentials
so the `cml runner` successfully ran from the invoked system but the cml.sh did not get the creds for termination because the template only refs …
=> GCP auth logic

iterative/resource_task.go
Indirectly closes #314 and mitigates a heap of different issues; ~requires manual testing on actual infrastructure. I'll script something later today to deplete my S3 quota~ tested and working.
=> Delete task resources when creation fails

iterative/resource_task.go, task/aws/resources/resource_auto_scaling_group.go, task/aws/task.go, task/az/resources/resource_virtual_machine_scale_set.go, task/az/task.go, task/common/machine/script.go, task/common/machine/storage.go, task/common/values.go, task/gcp/resources/resource_instance_group_manager.go, task/gcp/task.go, task/k8s/resources/resource_job.go, task/k8s/task.go, task/task.go, task/task_test.go
- Closes #319; see [#318](https://github.com/iterative/terraform-provider-iterative/pull/318#issuecomment-982728169) for an explanation of the `ExecStart=-` syntax.
- closes #321 with (guess it) pure `bash` 
- closes #297 with https://github.com/iterative/terraform-provider-iterative/pull/322/commits/b7520b08a8a441e63d1717fe39c9e7f62657e721 unless proven otherwise.
- partially fixes #330
=> Task status, heavy write fix and aws ips 

iterative/gcp/provider.go
This pull request allows `iterative_machine` and `iterative_cml_runner` users to specify custom `machine+accelerator*count` combinations (e.g. `custom-8-53248+nvidia-tesla-k80*1`) with the same syntax as the `iterative_task` resource. [(Discord)](https://discord.com/channels/485586884165107732/728693131557732403/938190175224348752)
=> Allow custom machine+gpu*count on runner cloud=gcp

iterative/resource_task.go
When `terraform apply` failed, the state file still retained a copy of the resource, and subsequent runs had no effect. 🙈  
```json
{
···
"resources": [
{
···
"instances": [
{
"status": "tainted",
···
}
]
}
]
}
```
=> Avoid taint on apply error

cml/setup.sh, iterative/resource_runner.go, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden, iterative/testdata/script_template_cloud_kubernetes.golden
In GCP the startup script is running every single boot this PR:
- checks that cml service is running to avoid setup the instance again
- checks is gpu is needed and reboots if not accessible  
- closes https://github.com/iterative/cml/issues/860
=> Reboot instance if gpu is not accesible

README.md, docs/guides/getting-started.md
Should we duplicate the [Getting Started](https://github.com/iterative/terraform-provider-iterative/blob/master/docs/guides/getting-started.md) guide here, or replace this snippet with a big link?
=> Improve basic example

iterative/gcp/provider.go, iterative/utils/helpers.go
The `instance_permission_set` could read:
- `sa@***.iam.gserviceaccount.com` (I think this should through a warning from use, no scopes does nothing 🙈 )
- `sa@***.iam.gserviceaccount.com,scopes=https://www.googleapis.com/auth/cloud-platform`
or using gcp's shorthand linked below
- `sa@***.iam.gserviceaccount.com,scopes=storage-rw,cloud-source-repos`
Slight oversight in some fine print found here: https://cloud.google.com/iam/docs/service-accounts#access_scopes
> Google Cloud now uses IAM, not access scopes, to specify permissions for Compute Engine instances. However, you are still required to set an access scope when you configure an instance to impersonate a service account
Scopes/Shorthand for reference: https://cloud.google.com/sdk/gcloud/reference/alpha/compute/instances/set-scopes …
=> Allow for specify scopes for assigned service account

cml/clone-amis.go
* Each goroutine must call wg.Done() otherwise wg.Wait() forever
=> cml: resolve deadlock when cloning amis (#404)

docs/guides/getting-started.md, docs/resources/task.md, iterative/resource_task.go
- closes #303
When `output` was unset, `""` or `null` it implicitly mirrored the value of `input`.
```hcl
resource "iterative_task" "example" {
···
workdir {
input = "/path/to/input"
}
}
```
When `output` is unset, `""` or `null` it will be disabled. Doesn't implicitly take the value of `input` anymore.
```hcl
resource "iterative_task" "example" {
···
workdir {
input = "/path/to/input"
output = "/path/to/output"
}
}
```
=> Separate input and output directory settings

task/aws/resources/data_source_image.go, task/az/resources/resource_virtual_machine_scale_set.go, task/gcp/resources/data_source_image.go, task/k8s/resources/resource_job.go
[NVIDIA NGC](https://docs.nvidia.com/ngc/ngc-deploy-public-cloud) offers machine and container images with **GPU drivers** and **Docker with GPU support** out of the box for [`aws`](https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-aws/#ami-overview), [`az`](https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-azure/#overview), [`gcp`](https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-gcp/index.html#overview), [`k8s`](https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-deploy-containers/index.html) and other platforms.
We are “maintaining” custom AWS machine images (https://github.com/iterative/terraform-provider-iterative/pull/206) that offer the same packages, plus Node.js for running the CML source distribution. After …
=> Add NVIDIA NGC image aliases

.github/workflows/smoke.yml
Part of https://github.com/iterative/itops/issues/111, ready to merge after https://github.com/iterative/itops/pull/192. ⚠️ Don't remove the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` secrets yet, because [`build-cml-ami.yml`](https://github.com/iterative/terraform-provider-iterative/blob/4fc3ee9192fa41a6ee57e9a54c00c79cbeba5c17/.github/workflows/build-cml-ami.yml) still relies on them. Partially closes https://github.com/iterative/itops/issues/111.
=> Move task tests to AWS sandbox (OIDC)

README.md, docs/guides/getting-started.md, docs/index.md, docs/resources/task.md
- add links to authentication credentials docs
- explain "auto-destroy unused resources"
- explain `script` usage (heredoc, `file()`, relative to `workdir.input`)
=> task docs improvements

go.mod, go.sum, iterative/resource_runner.go, iterative/resource_runner_test.go, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden, iterative/testdata/script_template_cloud_kubernetes.golden, iterative/utils/helpers.go
I haven't played with the task branch yet so, with those changes in mind how relevant would the following be?
I want to be able to target a specific cml version here: https://github.com/iterative/terraform-provider-iterative/blob/8121c664c4cc557059e44a332636d61a715c21dd/iterative/resource_runner.go#L288 similar to [this](https://github.com/iterative/setup-cml/pull/51)
----
adding an optional `cml_version` / defaulting to `@dvcorg/cml`
https://github.com/iterative/terraform-provider-iterative/blob/8121c664c4cc557059e44a332636d61a715c21dd/iterative/resource_runner.go#L409-L433
Thoughts @DavidGOrtega @0x2b3bfa0 ?
=> Allow for configuring a specific CML version

.github/workflows/smoke.yml
This pull request enables automatic smoke tests on internal pull requests, and limits concurrency to 1.
* Pushing a new commit to a pull request when tests are running will cancel the current run and and start a new one.
* Pushing a new commit to a pull request when tests are running in another pull request will just queue the tests.
=> Add concurrency limit to smoke tests

iterative/resource_task.go, task/aws/task.go, task/az/task.go, task/common/machine/storage.go, task/gcp/task.go, task/k8s/task.go, task/task.go, task/task_test.go
* Rename `workdir` to `storage` (conceptually useful for [#299](https://github.com/iterative/terraform-provider-iterative/issues/299), but dispensable)
* Alter the behavior of `storage.output` as proposed in [#414 (comment)](https://github.com/iterative/terraform-provider-iterative/issues/414#issuecomment-1061321093)
* Check that files not in `storage.output` aren't being downloaded
* Check that files in `storage.output` are being downloaded
=> task: rename `workdir.input` => `storage.workdir` & make `output` a subpath

task/common/cloud.go
This code was moved to [`task/common/identifier.go`](https://github.com/iterative/terraform-provider-iterative/blob/master/task/common/identifier.go) long ago. 🤦🏼‍♂️
=> Remove dead code from cloud.go

task/aws/resources/resource_bucket.go
Because of reasons yet unknown to me, `rclone` recursive deletion code introduced with #420 is flaky:
https://github.com/iterative/terraform-provider-iterative/blob/d5c4d1e19a0348dd7e779ae020588109c5cca7c3/task/common/machine/storage.go#L126-L151
This pull request restores the old cloud–specific code that goes through all the objects and deletes them as part of the `destroy` operation.
Closes #452.
=> Revert #420 for `aws`

iterative/resource_runner.go, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden, iterative/testdata/script_template_cloud_kubernetes.golden, iterative/utils/helpers.go
Fixes https://github.com/iterative/cml/issues/920, but is just a hack; don't merge unless we don't find a better solution.
=> Fix running CML inside CML with `pkg` binaries

iterative/resource_runner.go
Destroy the instance if the runner is unavailable
- closes https://github.com/iterative/cml/issues/926
=> Destroy instance if runner does not sync

task/common/machine/storage.go
Follow–up of #463; reports progress every two[^1] seconds:
```
2022-03-30T20:46:36.483Z [INFO]  provider.terraform-provider-iterative: [INFO] 🚀TPI Transferring 20kB (1000 files)...
iterative_task.example: Still destroying... [id=tpi-1o2y2wegfd8kq-3kmdmwbs-3dhqcjg6, 40s elapsed]
2022-03-30T20:46:38.483Z [INFO]  provider.terraform-provider-iterative: [INFO] 🚀TPI         300 B / 400 B, 75%, 0 B/s, ETA - (xfr#15/24)
2022-03-30T20:46:40.484Z [INFO]  provider.terraform-provider-iterative: [INFO] 🚀TPI     1.230 KiB / 1.934 KiB, 64%, 439 B/s, ETA 1s (xfr#63/103)
2022-03-30T20:46:42.483Z [INFO]  provider.terraform-provider-iterative: [INFO] 🚀TPI     2.188 KiB / 3.477 KiB, 63%, 469 B/s, ETA 2s (xfr#112/182)
2022-03-30T20:46:44.483Z [INFO]  provider.terraform-provider-iterative: [INFO] 🚀TPI …
```
=> Display real-time progress while transferring data

task/common/machine/script.go
Before, the `makeConfigPath` function returned [a default path](https://github.com/rclone/rclone/blob/7b7d780fffd8981e48c89096ef0e14400e625ca5/fs/config/config.go#L276), producing an [unhelpful warning message](https://github.com/rclone/rclone/blob/7b7d780fffd8981e48c89096ef0e14400e625ca5/fs/config/config.go#L359). Setting the `RCLONE_CONFIG` environment variable to to an empty string [causes](https://github.com/rclone/rclone/blob/7b7d780fffd8981e48c89096ef0e14400e625ca5/fs/config/config.go#L246) that function to return a bit [earlier](https://github.com/rclone/rclone/blob/7b7d780fffd8981e48c89096ef0e14400e625ca5/fs/config/config.go#L272), and causing [`configPath`](https://github.com/rclone/rclone/blob/7b7d780fffd8981e48c89096ef0e14400e625ca5/fs/config/config.go#L110) to be an empty …
=> Avoid `rclone` error message on task logs

go.mod, go.sum, iterative/utils/logger.go, iterative/utils/logger_test.go, task/aws/task.go, task/az/task.go, task/gcp/task.go, task/k8s/task.go
This pull request introduces some visual and conceptual improvements to the `TF_LOG_PROVIDER=INFO` internal logs. This approach is still fairly unideal beyond all remedy, but at least is easier on the eyes for ANSI terminal users; see https://github.com/iterative/terraform-provider-iterative/pull/423#pullrequestreview-901140497 for context.
=> Improve TF_LOG_PROVIDER logs

task/common/machine/storage.go
Closes #482; it turns out that `+ /./**` doesn't work but `+ /**` does, and we have to call `filepath.Clean` one more time after converting paths to absolute.
=> Fix `rclone` filters when `output` is `.`

.gitignore, README.md, docs/guides/authentication.md, docs/guides/getting-started.md, docs/index.md, docs/resources/task.md
=> docs: misc updates

iterative/gcp/provider.go, iterative/utils/helpers.go
After much experimentation and reading, I believe this to be the best option for supporting GCP's OIDC credentials.
I will caveat that we should include a docs warning that OIDC credentials from both AWS and GCP are only valid for an hour out of the box /CC myself https://github.com/iterative/cml.dev/pull/208
=> Coerce Credentials to handle GCP OIDC

iterative/gcp/provider.go, iterative/resource_runner.go, iterative/testdata/script_template_cloud_gcp.golden, iterative/utils/helpers.go
There is no need of duplicating the behavior of the [`google.FindDefaultCredentials`](https://pkg.go.dev/golang.org/x/oauth2/google#FindDefaultCredentials) function.
The only custom credential source we introduce is `GOOGLE_APPLICATION_CREDENTIALS_DATA` and only because it's not supported yet:
* https://github.com/googleapis/google-api-go-client/issues/185
=> Simplify Google Cloud credential detection

go.mod, iterative/resource_task.go, task/k8s/resources/common.go, task/k8s/task.go
This fixes the eternal issue with the flaky Kubernetes smoke tests. It also affected the normal operation of the provider in some circumstances.
=> Fix Kubernetes pod waiting flakiness

task/common/machine/script.go
This pull request removes quite a few bytes (~60%) from the log prefixes on the `machine`–based backends: `aws`, `az` & `gcp`
```console
TPI [INFO] LOG 0 >> Apr 16 11:11:16 ip-172-31-19-65 tpi-task[1572]: hello world 
```
```console
TPI [INFO] LOG 0 >> 2022-04-16 11:11:16 hello world
```
=> Improve log format for the `machine` backend

iterative/utils/logger.go
The length of the time string varies depending on the user timezone, and it breaks the count of padding spaces on timezones other than UTC. Time format copied from [hashicorp/go-hclog@b6b5567/intlogger.go:26](https://github.com/hashicorp/go-hclog/blob/b6b55671f4e5b82443139ee3e9f4417603c4cd72/intlogger.go#L26).
```console
TPI [INFO] LOG 0 >> Apr 16 16:36:01 ip-172-31-31-201 tpi-task[1930]: 56                 O]
TPI [INFO] Status: running •                                                          NFO]
```
```console
TPI [INFO] LOG 0 >> Apr 16 16:36:01 ip-172-31-31-201 tpi-task[1930]: 56                   
TPI [INFO] Status: running •                                                              
```
```go
package main
import (
"fmt"
"time"
)
func main() {
t := …
```
=> Fix TF_LOG `\r` hack for timezones other than UTC

task/common/machine/script.go
Redundant and not consistent across backends (see Kubernetes)
```
-- Logs begin at Sat 2022-04-16 16:34:38 UTC, end at Sat 2022-04-16 16:36:01 UTC
```
=> Remove `journalctl` header and footer

task/k8s/resources/resource_job.go
For consistency with the other backends
=> Add timestamps to `k8s` logs

iterative/resource_task.go, iterative/utils/analytics.go, main.go
Cascade on #493
* Sends `panic` contents and stack trace as part of analytics
* Runs analytics in the background and waits `Timeout` seconds for them to complete on exit
* Honors the analytics kill switches from the specification
* Renames some environment variables
~[Question: is `?ip_policy=strict` needed?](https://iterativeai.slack.com/archives/C0249LW0HAQ/p1650371913116649?thread_ts=1649179052.132839&cid=C0249LW0HAQ)~ Yes, see https://github.com/iterative/terraform-provider-iterative/pull/538/commits/dc3f90c1904d07851f775fcc74687b4e52690321
~We may want to use a clean context for analytics so it doesn't get cancellation signals from Terraform.~ Yes, see https://github.com/iterative/terraform-provider-iterative/pull/538/commits/f4d153d8cb635f1d44bdb64380f76e1aae6dad11
=> Add panic handling and background analytics

environment/setup.sh, iterative/gcp/provider.go, iterative/resource_runner.go, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden
You can only generate one access token per oidc authorization, so if oidc creds are used we need to pass the access_token to the instance to properly self-terminate.
Closes: https://github.com/iterative/cml/issues/989
=> Proper GCP - OIDC termination

iterative/utils/logger.go, task/common/machine/storage.go
Closes #566 and redirects `rclone` notices to the `[DEBUG]` level.
=> Fix data synchronization logs

task/aws/resources/resource_launch_template.go, task/az/resources/resource_virtual_machine_scale_set.go, task/common/machine/script.go, task/gcp/resources/resource_instance_template.go
Closes #561 and fixes #581; not tested locally, waiting for continuous integration to complain if I “committed” some mistake.
=> Separate credentials from other environment variables

iterative/utils/logger.go
```
TPI [INFO] Status: completed successfully •                                           ]
```
```
TPI [INFO] Status: completed successfully •                                           
```
=> Fix stray brackets on status messages

README.md
- vis. https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/
=> new dark/light sequel

task/aws/resources/data_source_image.go
Apparently, they disappear when a new image is published
=> Avoid pinning `aws` GPU images to a specific date

docs/resources/task.md, iterative/resource_task.go
```hcl
resource "iterative_task" "example" {
···
tags = {
Something = "Useful"
}
}
```
Closes #598
=> Add resource tagging support

docs/guides/permissions/gcp/main.tf
When I first attempted to deploy this to a newly created Google project this additional permission is required as all `cml` runners are placed in the `iterative` network by default, which will be created by the provider if it doesn't exist already, hence the additional perm.
=> Add `compute.networks.create` to `gcp` role in permissions doc example `main.tf`

.devcontainer.json
Part of #615, also speeds up Terraform and Packer installation, although `apt` is arguably more secure.
=> Use Go `devcontainer` and extension

iterative/utils/analytics.go
=> telemetry string/re-assignment tweaks

iterative/utils/analytics.go
updated spec to be more compatible
=> keep JSON format

environment/setup.sh, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden
Continuation of #628. Packer provisioners, unlike the startup script, don't run as root. 🙈
=> Add missing `sudo` on `setup.sh`

task/common/identifier.go, task/common/identifier_test.go
:hear_no_evil: Much sad! 8 hrs of debugging for such a small fix :see_no_evil:
my day's TLDR:
Any id/name greater than 28 aka: `maximumLongLength-shortLength-uint32(len("tpi---"))` resulted in improperly generating the digest and so the inferred bucket name was different from `terraform create` to `terraform refresh` which results in the follow error: 
Discovered via some BB testing because below  Bitbucket CI env is a uuid and thus `>28` you can also replicate the error by setting a `name` for your task that is also `>28` chars:
https://github.com/iterative/terraform-provider-iterative/blob/c3f1c08c60d32b954e8e23b23feae2e7431100c5/iterative/resource_task.go#L371-L388
=> `task` Fix id-generation

.github/workflows/build-ami.yml, .github/workflows/release.yml, .github/workflows/smoke.yml, Makefile, task/task_smoke_test.go
There should be a clear separation of unit and smoke/integration tests.
=> Use go build tags to separate task smoke tests

cmd/create/create.go, cmd/root.go
Closes #638; convoluted workaround to keep `cobra` instead of `viper` as the primary schema.
=> Parse nested maps from viper configuration

task/common/values.go
Legitimate use cases for anonymous fields are few and far between. This is not one of them - we're not accessing properties of the anonymous fields directly.
=> Use named fields instead of anonymous fields in common.Task

cmd/create/create.go, docs/resources/task.md, iterative/azure/provider.go, iterative/resource_machine.go, task/aws/resources/data_source_permission_set.go, task/az/resources/data_source_permission_set.go, task/az/resources/data_source_permission_set_test.go, task/az/task.go
This PR addresses #559 
The instance-permission-set is parsed as a comma-separated list of ARM resource ids in the form
'/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.
=> Add support for instance-permission-set in azure

environment/setup.sh, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden
similar to the ecr/aws use case.
where gitlab-ci `DOCKER_AUTH_CONFIG`:
```yml
{"credHelpers": { "us-west1-docker.pkg.dev": "gcr"}}
```
```
stages:
- deploy
- train
deploy_job:
stage: deploy
when: always
image: iterativeai/cml
script:
- cml-runner
--cloud gcp
--cloud-region us-west
--cloud-type e2-highcpu-2
--cloud-permission-set=permission-set-test@cml-gcp-test.iam.gserviceaccount.com,scopes=storage-rw 
--labels=cml-runner
train_job:
stage: train
when: on_success
needs: [deploy_job]
image: us-west1-docker.pkg.dev/cml-gcp-test/cml-test/cml:latest
tags:
- cml-runner
script:
- echo "hello"
- cml --version
```
related: https://github.com/iterative/terraform-provider-iterative/issues/627
when published/released closes: https://github.com/iterative/cml/issues/1136
=> add gcr/gcp docker helper

task/aws/resources/resource_bucket.go, task/aws/task.go, task/az/task.go, task/common/steps.go, task/common/steps_test.go, task/gcp/task.go, task/k8s/task.go
Defining steps as a slice of structures at least removes the necessity
to renumber the progress indicator when inserting new steps (or removin
them).
=> Restructure how resource allocation/deallocation/read steps are defined and executed

iterative/azure/provider.go
As per discord/tpi#1014906941308403803, it seems like #632 broke runners on Microsoft Azure. 🙈 
```
Error: Failed creating the machine: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingIdentityIds" Message="The identity ids must not be null or empty for 'UserAssigned' identity type."
```
=> Fix identities on Microsoft Azure runners

cmd/create/create.go
Suggested by @tasdomas, simplifies manual cleanup if the process fails
=> Print identifier before creating resources

cmd/create/create.go, go.mod, go.sum, iterative/resource_task.go, task/common/identifier.go, task/common/identifier_test.go, task/task.go, task/task_smoke_test.go
Now users can run e.g. `task create --name experiment` to create a task named `experiment` with a randomly generated suffix, avoiding clashes due to cloud providers' globally unique resource name requirements.
> **Note**
> Terraform resources' behavior remains unaltered and fully backwards-compatible. This change only affects the standalone command-line tool.
=> Implement human-readable random identifier generation

cmd/create/create.go, iterative/kubernetes/provider.go, task/aws/task.go, task/az/resources/resource_virtual_machine_scale_set.go, task/az/task.go, task/common/values.go, task/gcp/task.go, task/k8s/resources/resource_job.go, task/k8s/task.go
* K8s tags are currently being pulled from the `Task` object (where they are always empty) instead of the correct `Cloud` object.
* When custom label are added to a k8s job, the automatically added controller-uid label disappears from the `ObjectMeta`, which then breaks things like waiting for the job to be created, etc.
* Pull the tags from `Cloud`
* Use the job's `Spec.Selector.MatchLabels` instead of `ObjectMeta` to retrieve `controller-uid`
This is what `kubectl describe job` shows on master:
**Without custom labels/tags:**
```yaml
Labels:         controller-uid=5cf76b42-cbc8-484a-b496-6b867182e523
job-name=tpi-3aw4vu6287ot1-2biu93iu-1tw3q6af
Annotations:    batch.kubernetes.io/job-tracking: 
```
**With labels:**
```yaml
Labels:         app.kubernetes.io/instance=jenkins
Annotations: …
```
=> Fix k8s tag propagation and controller-uid detection

docs/resources/task.md, task/k8s/resources/resource_job.go
* Adds the ability to use the `region` field of the task in the Terraform file to pass node selector labels to the job.
* Expected format is comma-delimited `key=value` pairs
* e.g.  `region: foo=bar,goo=baz,...`
* Hacky?
=> Use `region` field as comma-delimited node selector for k8s

iterative/aws/provider.go
Closes #668, tested with this minimal example:
```hcl
terraform {
required_providers {
iterative = {
source = "github.com/iterative/iterative"
}
}
}
provider "iterative" {}
resource "iterative_machine" "example" {
cloud         = "aws"
region        = "eu-central-1"
instance_type = "g4dn.2xlarge"
}
```
=> Automate AWS availability zone selection

.github/workflows/smoke.yml
Partially reverts #680 for `az` because #684 is technicallly inviable and alternatives would require too much effort to implement. Still, `k8s` will remain using OpenID Connect.
=> Revert OIDC changes for `az` tests

environment/setup.sh, iterative/testdata/script_template_cloud_aws.golden, iterative/testdata/script_template_cloud_azure.golden, iterative/testdata/script_template_cloud_gcp.golden, iterative/testdata/script_template_cloud_invalid.golden, iterative/utils/analytics.go
Replaced the deprecated nvidia package with the new `nvidia-container-utils` as mentioned in the official [documentation](https://github.com/NVIDIA/nvidia-docker/tree/36e7a11c52f300668099ee500791e07302810007)
=> Update nvidia container support package

.github/workflows/release.yml
[“Oderwise”](https://en.wikipedia.org/wiki/Blinkenlights) the tag bump step [fails](https://github.com/iterative/terraform-provider-iterative/actions/runs/3217043672/jobs/5259571435#step:5:45) and the release doesn't ever get published.
=> Use `fetch-depth: 0` for release workflow

cmd/leo/destroyrunner/destroyrunner.go, iterative/gcp/provider.go
Closes #694; releasing this change may cause a hiccup in some Google Cloud users' runners.
=> Use `d.Id()` on Google Cloud machines

task/task_smoke_test.go
It turns out that `sh` doesn't understand `test -v`
https://github.com/iterative/terraform-provider-iterative/actions/runs/3239053637/jobs/5307980798#step:5:645
=> Fix `test -v` on smoke tests

cmd/leo/create/create.go, cmd/leo/root.go, docs/resources/task.md, iterative/resource_task.go, task/aws/task.go, task/az/task.go, task/common/machine/storage.go, task/common/machine/storage_test.go, task/common/values.go, task/gcp/task.go, task/k8s/task.go, task/task.go
The rules support glob patterns and are defined relative to workdir.
Additionally terraform files are excluded by default.
Closes #590
=> Support for file exclusion rules

iterative/utils/analytics.go
Closes #703; @casperdcl invenit
=> Exclude error from successful analytics

iterative/utils/analytics.go
Thanks for bringing a bit of elegance to code comments, @casperdcl! https://github.com/iterative/terraform-provider-iterative/pull/704#discussion_r1008580659
=> Improve comment

.gitignore, Makefile
- Adding target to build `leo` and `terraform-provider-iterative` binaries in repo root
- `build` target now uses the above instead of the current "check-build" (checks validity, but produces no binaries, which might be useful)
- `install_tpi` target - built and installed `leo` bin into tf plugins (probably unwanted behavior) - fixed
- Added phony directives for phony targets (which also allows for the convenience of `make targets` which acts as `--help`)
- Some light refactoring
- Addition to gitignore for JB ideas
=> Makefile - Make it a bit more usable

cmd/leo/read/read.go
adds some simple feedback for when users run `leo read --follow` right after a `leo create` and there aren't any logs yet.
=> Simple waiting feedback for leo

cmd/leo/create/create.go, cmd/leo/delete/delete.go, task/aws/resources/data_source_image.go, task/az/resources/resource_virtual_machine_scale_set.go, task/common/steps.go, task/gcp/resources/data_source_image.go
the delete wasn't syncing back data because of the read: https://github.com/iterative/terraform-provider-iterative/blob/f84401cefa3896bd26152223eb78d055fa54673f/task/aws/task.go#L248
it would try to check the Image, fail because it was not set, and then bailout from the read and continue to delete resources.
I don't think this should be the permanent solution. I think we should either use smaller parts on the existing interfaces to leo doesn't make unneeded API calls (instead of blank read for the whole task), or have a leo shutdown/close that is better suited for this (natural ending of a task syncing changes) and save delete for cleaning up broken tasks
Closes: https://github.com/iterative/terraform-provider-iterative/issues/712
=> Fix leo read error for delete

go.mod, go.sum, task/aws/resources/resource_auto_scaling_group.go, task/aws/task.go, task/az/resources/resource_virtual_machine_scale_set.go, task/az/task.go, task/common/machine/storage.go, task/common/steps.go, task/gcp/resources/resource_instance_group_manager.go, task/gcp/task.go, task/k8s/task.go
The modifications introduced with this pull request can be used to provide detailed operation status, to avoid a a [“The Cloudformation”](https://twitter.com/_euank/status/996513864857481216) experience where users have no insight on the operation progress.
Uses [github.com/0x2b3bfa0/logrusctx](https://github.com/0x2b3bfa0/logrusctx), which is in turn based on [github.com/juju/zaputil/zapctx](https://pkg.go.dev/github.com/juju/zaputil/zapctx), mentioned by @tasdomas in a casual conversation, unsuspecting of my implementation impetus.
```go
logger := logrus.WithField("session", sesssionID)
logger.SetOutput(&buf)
ctx = logrusctx.WithLogger(ctx, logger)
tsk.Create(ctx)
// buf will contain the real-time progress of the operation
```
=> Use `logrusctx` instead of `logrus` on `task`

iterative/aws/provider.go, iterative/azure/provider.go, iterative/gcp/provider.go
ref: https://github.com/iterative/cml/issues/1145
https://github.com/iterative/terraform-provider-iterative/blob/fd4a94041fcf5bab312699342fdbed39ae8ebcb9/task/aws/resources/resource_launch_template.go#L61-L73
https://github.com/iterative/terraform-provider-iterative/blob/fd4a94041fcf5bab312699342fdbed39ae8ebcb9/task/az/resources/resource_virtual_machine_scale_set.go#L111-L123
https://github.com/iterative/terraform-provider-iterative/blob/fd4a94041fcf5bab312699342fdbed39ae8ebcb9/task/gcp/resources/resource_instance_template.go#L72-L84
=> Helper machine type parity with task

.github/workflows/build-ami.yml, .github/workflows/smoke.yml, README.md, docs/guides/authentication.md, docs/index.md
Better to do it before we start hardcoding the name of the main branch in other places
=> Rename `master` to `main`

.github/workflows/test-dummy.yml
The `test` and `lint` jobs in test.yml ignore changes to `docs/*` and
`**.md`. Since those checks are required, this results in blocked PRs.
This adds dummy tests to satisfy the required check statuses.
See #731.
=> Dummy test and lint jobs for ignored paths.

.github/workflows/build-ami.yml, environment/ami.pkr.hcl
With iterative/itops#890 we switched terraform project name from cml to `packer-infra` to be used also for Studio-Selfhosted packer builds. Additionaly I made a role to cooperate with OIDC.
=> Switch build-ami action to OIDC

iterative/kubernetes/provider.go
Closes https://github.com/iterative/cml/issues/1361
=> Port `task` instance types to `runner`

iterative/resource_task.go, task/common/machine/machine-script.sh.tpl, task/common/machine/testdata/machine_script_full.golden, task/common/machine/testdata/machine_script_minimal.golden
Adds bash logger to studio as #733 and #734 😁 
- closes partially https://github.com/iterative/leo-server/issues/36
=> Studio bash logger

iterative/kubernetes/provider.go
The documentation states a list of common machine types: https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#machine-type and https://github.com/iterative/terraform-provider-iterative/blob/main/docs/guides/generic-machine-types.md
I did notice the Kubernetes provider is missing the `s` machine type from the list. This pull request fixes this.
=> Add missing machine type to Kubernetes provider

Makefile
I had issues when using `make` with paths containing spaces. This PR fixes this.
Examples in the Dev Container configuration:
```sh
$ make leo
CGO_ENABLED=0 \
go build -ldflags="-s -w -X terraform-provider-iterative/iterative/utils.Version=0.0.1680607982+development" \
-o /workspaces/509.20.06 terraform-provider-iterative/leo \
/workspaces/509.20.06 terraform-provider-iterative/cmd/leo
package terraform-provider-iterative/leo is not in GOROOT (/usr/local/go/src/terraform-provider-iterative/leo)
stat /workspaces/509.20.06: directory not found
make: *** [Makefile:29: leo] Error 1
```
```sh
$ make tpi
CGO_ENABLED=0 \
go build -ldflags="-s -w -X terraform-provider-iterative/iterative/utils.Version=0.0.1680608415+development" \
-o /workspaces/509.20.06 …
```
=> Support paths with spaces when using make

environment/ami.pkr.hcl
During cleaning the SG's in region I accidentally deleted the group used for build ;-(
=> Set new SecurityGroup ID

iterative/aws/provider.go
```
Stack trace from the terraform-provider-iterative plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14c79f3]
goroutine 49 [running]:
terraform-provider-iterative/iterative/aws.ResourceMachineCreate({0x4095a90, 0xc0006c5560}, 0xc00090b900, {0x31cda80?, 0xc00033c2d0?})
terraform-provider-iterative/iterative/aws/provider.go:129 +0x17d3
terraform-provider-iterative/iterative.resourceMachineCreate({0x4095a90, 0xc0006c5560}, 0xe?, {0x0, 0x0})
terraform-provider-iterative/iterative/resource_machine.go:193 +0x765
terraform-provider-iterative/iterative.resourceRunnerCreate({0x4095a90?, 0xc0006c5560}, 0xc00090b900, {0x0?, 0x0})
terraform-provider-iterative/iterative/resource_runner.go:240 +0x578 …
```
=> Add misssing error check

iterative/kubernetes/provider.go, iterative/resource_machine.go, iterative/resource_runner.go, task/k8s/resources/resource_job.go
This PR implements the Kubernetes arbitrary node selector described in issue https://github.com/iterative/cml/issues/1365.
This is a work in progress and my first experience with Golang and Terraform provider development, I'm open to improvements.
Related PRs:
- https://github.com/iterative/cml/pull/1370
- https://github.com/iterative/cml.dev/pull/464
=> Add support for Kubernetes arbitrary node selector

task/aws/resources/resource_key_pair.go
This is a step to detect conditions under which we get a panic referencing the results (#57).
=> Check if DescribeKeyPairs returns a result.
